### ISSUE TITLE
species object

### ISSUE THREAD

**Issue by Tang-pro** [yollct/spycone#4]
Hi, @yollct @kadam0 
`dset = spy.dataset(ts=data,
        transcript_id=transcriptid,
        gene_id = geneid,
        species=9606,
        keytype='entrezgeneid',
        timepts=4, reps1=3)`
Can I ask if I can use non-model species here, like cotton, because I see that the code has some parameters and species need to be provided

**Comment by Tang-pro** [comment]
Hi, @yollct @kadam0 
Here my species is cotton, and the annotation information, which is not the NCBI version, is from the cotton website cottongen, here is how to solve it. Also I don't have BioNetwork, but I just want to cluster isoform-switch, does this affect

**Comment by yollct** [comment]
Hi,

No it doesn't affect if you just use the isoform-switch function. You can input any species in this case.

Best,
Chit Tong
